name: Claude README Sync (PR-triggered, 7-day analysis)
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  readme-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full history to analyze last 7 days
          # Remove the ref parameter to work with the default checkout behavior
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Switch to main branch for analysis
        run: |
          git checkout ${{ github.event.repository.default_branch }}
          git pull origin ${{ github.event.repository.default_branch }}
      
      - name: Setup GitHub CLI
        run: |
          # Ensure gh is authenticated
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
      
      - name: Analyze last 7 days of changes
        id: analyze-changes
        run: |
          echo "=== Analyzing changes from last 7 days ==="
          
          # Get commits from last 7 days
          SINCE_DATE=$(date -d '7 days ago' --iso-8601)
          echo "Checking changes since: $SINCE_DATE"
          
          # Get changed files in the last week
          echo "Files changed in last 7 days:"
          CHANGED_FILES=$(git log --since="$SINCE_DATE" --name-only --pretty=format: \
            | sort -u \
            | grep -v '^$' \
            | head -50)
          echo "$CHANGED_FILES"
          
          # Get commit count and summary
          RECENT_COMMITS=$(git log --since="$SINCE_DATE" --oneline)
          COMMIT_COUNT=$(echo "$RECENT_COMMITS" | wc -l)
          
          echo "=== Commits from last 7 days ($COMMIT_COUNT total) ==="
          echo "$RECENT_COMMITS"
          
          # Generate unique branch name
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          BRANCH_NAME="readme-sync-${TIMESTAMP}"
          echo "Will create branch: $BRANCH_NAME"
          
          # Save to environment
          {
            echo "CHANGED_FILES<<EOF"
            echo "$CHANGED_FILES"
            echo "EOF"
            echo "COMMIT_COUNT=$COMMIT_COUNT"
            echo "SINCE_DATE=$SINCE_DATE"
            echo "BRANCH_NAME=$BRANCH_NAME"
          } >> $GITHUB_ENV
          
          # Check if we have changes to analyze
          if [ "$COMMIT_COUNT" -eq "0" ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
            echo "No commits in the last 7 days"
          else
            echo "skip=false" >> $GITHUB_OUTPUT
            echo "Found $COMMIT_COUNT commits to analyze"
          fi
      
      - name: Sync README with Claude (Create Separate PR)
        if: steps.analyze-changes.outputs.skip != 'true'
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          timeout_minutes: "45"
          allowed_tools: "Bash(git status),Bash(git branch),Bash(git log --since='${{ env.SINCE_DATE }}' --oneline),Bash(git log --since='${{ env.SINCE_DATE }}' --name-only --pretty=format:),Bash(git diff --name-only HEAD~${{ env.COMMIT_COUNT }}..HEAD),Bash(git diff HEAD~${{ env.COMMIT_COUNT }}..HEAD),Bash(git fetch origin),Bash(git checkout ${{ github.event.repository.default_branch }}),Bash(git pull origin ${{ github.event.repository.default_branch }}),Bash(git checkout -b ${{ env.BRANCH_NAME }}),Bash(git config --global user.name 'Claude Bot'),Bash(git config --global user.email 'claude-bot@anthropic.com'),Bash(git add README.md),Bash(git commit -m*),Bash(git push origin ${{ env.BRANCH_NAME }}),Bash(gh pr create --title* --body* --base ${{ github.event.repository.default_branch }} --head ${{ env.BRANCH_NAME }}),Bash(gh pr comment ${{ github.event.pull_request.number }} --body*),View,GlobTool,GrepTool,BatchTool,Edit"
          direct_prompt: |
            I need you to analyze the code changes from the last 7 days, update the README.md, and create a separate pull request with those changes.
            
            **IMPORTANT: You must work from the main branch and create a completely separate branch/PR**
            
            Please follow these steps carefully:
            
            **Step 1: Ensure Clean State**
            1. Run `git status` to check current state
            2. Run `git branch` to see current branch
            3. Run `git fetch origin` to get latest changes
            4. Run `git checkout ${{ github.event.repository.default_branch }}` to ensure you're on main
            5. Run `git pull origin ${{ github.event.repository.default_branch }}` to get latest main
            
            **Step 2: Understand Recent Activity**
            6. Run `git log --since='${{ env.SINCE_DATE }}' --oneline` to see all commits from the last week
            7. Run `git log --since='${{ env.SINCE_DATE }}' --name-only --pretty=format:` to see which files changed
            8. Run `git diff --name-only HEAD~${{ env.COMMIT_COUNT }}..HEAD` for a clean list of changed files
            9. Run `git diff HEAD~${{ env.COMMIT_COUNT }}..HEAD` to see the actual code changes
            
            **Step 3: README Analysis & Update**
            10. Read and understand the current README.md content
            11. Analyze all the changes from the past 7 days to understand what functionality has been added, modified, or removed
            12. Update the README.md to reflect these accumulated changes
            
            **Step 4: Create New Branch & Commit (CRITICAL STEP)**
            13. **MUST DO**: Create a new branch from main: `git checkout -b ${{ env.BRANCH_NAME }}`
            14. Verify you're on the new branch: `git branch` (should show * next to ${{ env.BRANCH_NAME }})
            15. Configure git: `git config --global user.name 'Claude Bot'` and `git config --global user.email 'claude-bot@anthropic.com'`
            16. Stage your changes: `git add README.md`
            17. Commit with a descriptive message: `git commit -m "docs: update README based on 7-day analysis - [brief description of main changes]"`
            18. Push the new branch: `git push origin ${{ env.BRANCH_NAME }}`
            
            **Step 5: Create Pull Request**
            19. Create a pull request: `gh pr create --title "📝 README Update - 7-day Analysis" --body "[Detailed description of changes including:
                - Analysis period: ${{ env.SINCE_DATE }} to now
                - Total commits analyzed: ${{ env.COMMIT_COUNT }}
                - Main changes discovered
                - README sections updated
                - Relationship to recent development activity]" --base ${{ github.event.repository.default_branch }} --head ${{ env.BRANCH_NAME }}`
            
            **Step 6: Comment on Triggering PR**
            20. Add a comment to the triggering PR: `gh pr comment ${{ github.event.pull_request.number }} --body "🤖 **README Update Created**
            
                I've analyzed the last 7 days of development activity and created a separate PR to update the README:
                
                - **Analysis Period**: ${{ env.SINCE_DATE }} to now
                - **Commits Analyzed**: ${{ env.COMMIT_COUNT }}
                - **New PR Branch**: ${{ env.BRANCH_NAME }}
                
                The README update PR includes documentation for recent changes and will be linked here once created."`
            
            **Guidelines for README updates:**
            - Focus on consolidating changes rather than individual commits
            - Update multiple README sections if needed (installation, usage, API docs, features, etc.)
            - Maintain the existing README structure and tone
            - Be specific about what changed and include examples for new features
            - If no significant updates are needed, don't create a PR, just comment explaining why
            
            **Context:**
            - Analysis period: Last 7 days (since ${{ env.SINCE_DATE }})
            - Total commits found: ${{ env.COMMIT_COUNT }}
            - Triggering PR: #${{ github.event.pull_request.number }} - "${{ github.event.pull_request.title }}"
            - New branch name: ${{ env.BRANCH_NAME }}
            - Base branch: ${{ github.event.repository.default_branch }}
            
            **CRITICAL REMINDER**: You MUST create a new branch (${{ env.BRANCH_NAME }}) from main, make changes there, and create a separate PR. Do NOT commit to the existing PR branch.
