name: Claude README Sync (PR-triggered, 7-day analysis)

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  readme-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full history to analyze last 7 days
          ref: main  # Always checkout main branch as base
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Analyze last 7 days of changes
        id: analyze-changes
        run: |
          echo "=== Analyzing changes from last 7 days ==="
          
          # Get commits from last 7 days
          SINCE_DATE=$(date -d '7 days ago' --iso-8601)
          echo "Checking changes since: $SINCE_DATE"
          
          # Get changed files in the last week
          echo "Files changed in last 7 days:"
          CHANGED_FILES=$(git log --since="$SINCE_DATE" --name-only --pretty=format: \
            | sort -u \
            | grep -v '^$' \
            | head -50)
          echo "$CHANGED_FILES"
          
          # Get commit count and summary
          RECENT_COMMITS=$(git log --since="$SINCE_DATE" --oneline)
          COMMIT_COUNT=$(echo "$RECENT_COMMITS" | wc -l)
          
          echo "=== Commits from last 7 days ($COMMIT_COUNT total) ==="
          echo "$RECENT_COMMITS"
          
          # Generate unique branch name
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          BRANCH_NAME="readme-sync-${TIMESTAMP}"
          echo "Will create branch: $BRANCH_NAME"
          
          # Save to environment
          {
            echo "CHANGED_FILES<<EOF"
            echo "$CHANGED_FILES"
            echo "EOF"
            echo "COMMIT_COUNT=$COMMIT_COUNT"
            echo "SINCE_DATE=$SINCE_DATE"
            echo "BRANCH_NAME=$BRANCH_NAME"
          } >> $GITHUB_ENV
          
          # Check if we have changes to analyze
          if [ "$COMMIT_COUNT" -eq "0" ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
            echo "No commits in the last 7 days"
          else
            echo "skip=false" >> $GITHUB_OUTPUT
            echo "Found $COMMIT_COUNT commits to analyze"
          fi

      - name: Sync README with Claude and Create PR
        if: steps.analyze-changes.outputs.skip != 'true'
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          timeout_minutes: "45"
          allowed_tools: "Bash(git config*),Bash(git checkout*),Bash(git branch*),Bash(git status),Bash(git log*),Bash(git diff*),Bash(git add*),Bash(git commit*),Bash(git push*),Bash(echo*),View,GlobTool,GrepTool,BatchTool,Edit,mcp__github__get_file_contents, mcp__github__create_branch,mcp__github__create_pull_request,mcp__github__add_issue_comment,mcp__github_file_ops__commit_files"
          direct_prompt: |
            I need you to analyze the code changes from the last 7 days, update the README.md file, and create a separate pull request for the documentation updates.
            
            **IMPORTANT**: You need to create a NEW BRANCH for the README updates, not work on the current branch.
            
            Please follow these steps EXACTLY:
            
            **Step 1: Setup Git Configuration**
            1. Run `git config --global user.name 'Claude Bot'`
            2. Run `git config --global user.email 'claude-bot@anthropic.com'`
                      
            **Step 2: Analyze Recent Changes**
            3. Run `git log --since='${{ env.SINCE_DATE }}' --oneline` to see commits from the last week
            4. Run `git log --since='${{ env.SINCE_DATE }}' --name-only --pretty=format:` to see which files changed
            5. Run `git diff --name-only HEAD~${{ env.COMMIT_COUNT }}..HEAD 2>/dev/null || git log --name-only --pretty=format: -n ${{ env.COMMIT_COUNT }}` for changed files list
            6. Run `git diff HEAD~${{ env.COMMIT_COUNT }}..HEAD 2>/dev/null || git show --name-only` to see actual code changes
            
            **Step 4: README Analysis & Update**
            7. Read and understand the current README.md content
            8. Analyze all the changes from the past 7 days to understand what functionality has been added, modified, or removed

            **Step 2: Verify Current State and Create New Branch**
            9. Run `git status` to see current state
            10. Run `git branch --show-current` to see current branch
            11. Create and switch to new branch: `git checkout -b ${{ env.BRANCH_NAME }}`
            12. Verify you're on the new branch: `git branch --show-current`
            13. Update the README.md to reflect these accumulated changes (maintain existing structure and tone)
            
            **Step 5: Commit and Push Changes**
            14. If you made changes to README.md:
                - Run `git add README.md`
                - Run `git commit -m "docs: update README based on 7-day analysis - [brief description of changes]"`
                - Run `git push --set-upstream origin ${{ env.BRANCH_NAME }}`
                - Run `echo "README updated, committed, and pushed successfully"`
            15. If no changes were needed:
                - Run `echo "No README updates required - documentation is current"`
                - SKIP the remaining steps
            
            **Step 6: Create Pull Request (only if changes were made)**
            16. Create PR using GitHub CLI:
                ```bash
                gh pr create \
                  --title "📝 README Update - 7-day Analysis (triggered by PR #${{ github.event.pull_request.number }})" \
                  --body "## 🤖 Automated README Update
                
                This PR contains README updates based on analysis of the last 7 days of changes.
                
                **Triggered by:** PR #${{ github.event.pull_request.number }} - \"${{ github.event.pull_request.title }}\"
                
                **Analysis Period:** Last 7 days (since ${{ env.SINCE_DATE }})
                
                **Changes Analyzed:** ${{ env.COMMIT_COUNT }} commits
                
                ### Summary of Recent Activity 
                
                The README has been updated to reflect recent development changes and improvements.
                Why These README Changes Were Necessary
                
                ---
                
                *This PR was automatically created by Claude based on recent repository activity.*" \
                  --base main \
                  --head ${{ env.BRANCH_NAME }} \
                  --label "documentation,automated,readme-update"
                ```
            
            **Guidelines:**
            - Focus on consolidating changes rather than individual commits
            - Update multiple README sections if needed (installation, usage, API docs, features, etc.)
            - Maintain the existing README structure and tone
            - Be specific about what changed and include examples for new features
            - Use clear, descriptive commit messages
            
            **Context:**
            - Analysis period: Last 7 days (since ${{ env.SINCE_DATE }})
            - Total commits found: ${{ env.COMMIT_COUNT }}
            - New branch name: ${{ env.BRANCH_NAME }}
            - Triggering PR: #${{ github.event.pull_request.number }} - "${{ github.event.pull_request.title }}"
            
            **CRITICAL**: Make sure you create the new branch BEFORE making any changes, and push to that branch, not the current one!

      - name: Handle no changes case
        if: steps.analyze-changes.outputs.skip == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: `## ℹ️ No README Update Needed
              
              I analyzed the repository but found no commits in the last 7 days that would require README updates.
              
              The current README.md appears to be up to date.
              
              ---
              
              *This comment was automatically generated by Claude README Sync*`
            });
